apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlf
  namespace: default
spec:
  selector:
    matchLabels:
      run: dlf
  template:
    metadata:
      labels:
        run: dlf
    spec:
      containers:
      - image: asia-southeast1-docker.pkg.dev/johncollins/johncollins/dlf@sha256:c48a346de74aebb2850c50fb1d435d52d5c10ae0e2d4654763f61300c8279281
        imagePullPolicy: IfNotPresent
        name: dlf
        ports:
        - containerPort: 8080
          protocol: TCP


