apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlf
  namespace: default
spec:
  selector:
    matchLabels:
      run: dlf
  template:
    metadata:
      labels:
        run: dlf
    spec:
      containers:
      - image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
        imagePullPolicy: IfNotPresent
        name: dlf
        ports:
        - containerPort: 8080
          protocol: TCP


